server:
  port: 80

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: >
          jdbc:p6spy:mysql://localhost:3306/yjz?
          useSSL=true&
          useUnicode=true&
          characterEncoding=UTF-8&
          useTimezone=true&
          serverTimezone=GMT%2B8&
          allowMultiQueries=true&
          rewriteBatchedStatements=true
    username: root
    password: sasa

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  type-aliases-package: com.hsinghai.yzj.model
  mapper-locations: classpath*:com/hsinghai/yzj/repository/**/*.xml